FROM node:24.14.0

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npx prisma generate --schema=src/prisma/schema.prisma

RUN npm run build

RUN rm -rf ./src

EXPOSE 3001

# npm run start:dev
CMD ["npm", "run", "start:prod"]